/* 
 * RIDB API Additional Functions 0.1
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SearchAvailabilityOkPayloadQuotaTypeMaps {
  #[serde(rename = "ConstantQuotaUsageByStartDate")]
  constant_quota_usage_by_start_date: Option<::std::collections::HashMap<String, ::models::SearchEntry>>
}

impl SearchAvailabilityOkPayloadQuotaTypeMaps {
  pub fn new() -> SearchAvailabilityOkPayloadQuotaTypeMaps {
    SearchAvailabilityOkPayloadQuotaTypeMaps {
      constant_quota_usage_by_start_date: None
    }
  }

  pub fn set_constant_quota_usage_by_start_date(&mut self, constant_quota_usage_by_start_date: ::std::collections::HashMap<String, ::models::SearchEntry>) {
    self.constant_quota_usage_by_start_date = Some(constant_quota_usage_by_start_date);
  }

  pub fn with_constant_quota_usage_by_start_date(mut self, constant_quota_usage_by_start_date: ::std::collections::HashMap<String, ::models::SearchEntry>) -> SearchAvailabilityOkPayloadQuotaTypeMaps {
    self.constant_quota_usage_by_start_date = Some(constant_quota_usage_by_start_date);
    self
  }

  pub fn constant_quota_usage_by_start_date(&self) -> Option<&::std::collections::HashMap<String, ::models::SearchEntry>> {
    self.constant_quota_usage_by_start_date.as_ref()
  }

  pub fn reset_constant_quota_usage_by_start_date(&mut self) {
    self.constant_quota_usage_by_start_date = None;
  }

}



