/* 
 * RIDB API Additional Functions 0.1
 *
 * The Recreation Information Database (RIDB) provides data resources to citizens, offering a single point of access to information about recreational opportunities nationwide. The RIDB represents an authoritative source of information and services for millions of visitors to federal lands, historic sites, museums, and other attractions/resources. This initiative integrates multiple Federal channels and sources about recreation opportunities into a one-stop, searchable database of recreational areas nationwide.
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SearchAvailabilityOk {
  #[serde(rename = "payload")]
  payload: ::models::SearchAvailabilityOkPayload
}

impl SearchAvailabilityOk {
  pub fn new(payload: ::models::SearchAvailabilityOkPayload) -> SearchAvailabilityOk {
    SearchAvailabilityOk {
      payload: payload
    }
  }

  pub fn set_payload(&mut self, payload: ::models::SearchAvailabilityOkPayload) {
    self.payload = payload;
  }

  pub fn with_payload(mut self, payload: ::models::SearchAvailabilityOkPayload) -> SearchAvailabilityOk {
    self.payload = payload;
    self
  }

  pub fn payload(&self) -> &::models::SearchAvailabilityOkPayload {
    &self.payload
  }


}



